---

INPUT_CHAINS:
  - name: "INPUT_SSH"
    policy: "ACCEPT"
    rules:
      - "-s 0.0.0.0/0 -p tcp --dport 22 -j ACCEPT"
  - name: "INPUT_WEB"
    policy: "ACCEPT"
    rules:
      - "-s 0.0.0.0/0 -p tcp --dport 80 -j ACCEPT"

OUTPUT_CHAINS:
  - name: "OUTPUT_WEB"
    policy: "ACCEPT"
    rules:
      - "-d 0.0.0.0/0 -p tcp --dport 80 -j ACCEPT"
  - name: "OUTPUT_SSH"
    policy: "ACCEPT"
    rules:
      - "-d 0.0.0.0/0 -p tcp --dport 22 -j ACCEPT"

FORWARD_CHAINS:
  - name: "FORWARD_DEFAULT"
    policy: "DROP"
    rules:
      - "-s 0.0.0.0/0 -d 0.0.0.0/0 -j DROP"

LB_DOMAIN: app.sudoer.net

LB_BACKEND:
  - ip: 78.47.70.96
  - ip: 116.203.31.182
