---

- name: Install the latest version packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - "{{ FAIL2BAN_PKGS_LIST }}"
  tags:
    - pkg

- name: Update all packages
  apt:
    name: "*"
    state: latest
  tags:
    - pkg

- name: fail2ban config for ssh
  template:
    src: etc/fail2ban/jail.d/sshd.conf
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    restart fail2ban
