---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - sysstat
    - htop
    - tcpdump
    - lftp

- name: Create Directory
  file:
    state: directory
    path: "/tmp/nokhod"


